modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "druids"
version = "${version}"
displayName = "Druids (RPG Series Plus)"
authors = [ "Nutties", "EldarGods" ]
description = '''
Engulf foes in deadly vines and poison targets.
'''
#logoFile = ""

[[dependencies.druids]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druids]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druids]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.druids]]
modId = "more_rpg_classes"
type = "required"
versionRange = "[2.7.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druids]]
modId = "spell_engine"
type = "required"
versionRange = "[1.10.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druids]]
modId = "skill_tree_rpgs"
type = "required"
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.druids]]
modId = "armor_model_api"
type = "required"
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"