# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 0.5
release_type = beta
maven_group = io.github.rulft44
archives_name = druids
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.1
yarn_mappings_patch_neoforge_version = 1.21+build.6
