# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version=1.3
release_type=release
maven_group=io.github.rulft44
archives_name=druids
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
yarn_mappings_patch_neoforge_version=1.21+build.4

# Mod Loader
fabric=0.18.2
neo=21.1.248

# Dependencies
fapi=0.116.6+1.21.1
forgefapi=0.115.6+2.1.4+1.21.1

spell=1.10.3+1.21.1
mrpg=2.7.0+1.21.1

spellpow=1.6.0+1.21.1
ticonfig=3.1.1
rune=1.3.1+1.21.1

armormodel=1.0.0+1.21.1
cloth=15.0.140
playeranim=2.0.1+1.21.1

trinkets=3.10.0
curios=9.5.1+1.21.1

puffskills=0.16.7+1.21
skilltree=1.6.0+1.21.1
rangedapi=2.3.3+1.21.1

jei=19.25.0.323
