pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://files.minecraftforge.net/maven/' }
        gradlePluginPortal()
		maven {
			url "https://maven.firstdark.dev/releases"
		}
    }
}

rootProject.name = 'druids'

include 'common'
include 'fabric'
include 'neoforge'
