architectury {
    common enabled_platforms.split(',')
}

def platform = "fabric";

repositories {
    maven { url 'https://maven.kosmx.dev/' }
    maven { url 'https://maven.shedaniel.me/' }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Ladysnake Libs"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        url "https://cursemaven.com"
        content { includeGroup "curse.maven" }
    }
    maven { url 'https://maven.fabricmc.net' }
    maven { url 'https://maven.puffish.net' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://maven.blamejared.com/' }
    maven { url 'https://modmaven.dev' }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "dev.architectury:architectury:$architectury_api_version"

    modImplementation("dev.kosmx.player-anim:player-animation-lib-${platform}:${player_anim_version}")
    modImplementation("me.shedaniel.cloth:cloth-config-${platform}:${cloth_config_version}")

    modImplementation("maven.modrinth:armor-model-api:${armor_model_api_version}-${platform}")
    modImplementation("maven.modrinth:tiny-config:${tiny_config_version}-${platform}")
    modImplementation("maven.modrinth:spell-power:${spell_power_version}-${platform}")
    modImplementation("maven.modrinth:spell-engine:${spell_engine_version}-${platform}") { transitive = false }
    modImplementation("maven.modrinth:runes:${runes_version}-${platform}")
    modImplementation("maven.modrinth:more-rpg-library:${mrpg_version}-${platform}")
    modImplementation("maven.modrinth:skill-tree:${skilltree_version}-${platform}")
    modImplementation("maven.modrinth:ranged-weapon-api:${ranged_api_version}-${platform}")

    modImplementation("net.puffish:skillsmod:${pufferfish_skills_version}:${platform}")
}
