modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "druids"
version = "${version}"
displayName = "Druids (RPG Series Plus)"
authors = "Rulft"
description = '''
Engulf foes in deadly vines and poison targets.
'''
logoFile = "icon.png"

[[dependencies.druids]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druids]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druids]]
modId = "more_rpg_classes"
type = "required"
versionRange = "[2.5.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druids]]
modId = "spell_engine"
type = "required"
versionRange = "[1.9.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druids]]
modId = "skill_tree_rpgs"
type = "required"
versionRange = "[1.4.4,)"
ordering = "AFTER"
side = "BOTH"
